# CI/Manual Trigger
name: TestCafe Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test1:
    name: TestCafe Tests - (WINDOWS/HEADLESS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [20.x]
        headlessbrowser: [edge, chrome, firefox]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Run Tests (${{ matrix.headlessbrowser }}) Headless
      uses: DevExpress/testcafe-action@v0.0.6
      with:
        version: "3.7.2"
        args: ${{ matrix.headlessbrowser }}:headless -c 4 tests/
          
  test2:
    if: ${{ false }}  # Disable IE tests as IE is deprecated
    name: TestCafe Tests - (WINDOWS/IE)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [20.x]
        browser: [ie]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Run Tests (${{ matrix.browser }})
      uses: DevExpress/testcafe-action@v0.0.6
      with:
        version: "3.7.2"
        args: ${{ matrix.browser }} tests/
          
  test3:
    name: TestCafe Tests - (UBUNTU/HEADLESS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20.x]
        headlessbrowser: [edge, chrome, firefox]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Run Tests (${{ matrix.headlessbrowser }}) Headless
      uses: DevExpress/testcafe-action@v0.0.6
      with:
        version: "3.7.2"
        args: ${{ matrix.headlessbrowser }}:headless -c 4 tests/

  test4:
    if: ${{ false }}  # Disable Safari tests (Screen Recording permission issue on GitHub-hosted runners)
    name: TestCafe Tests - (MACOS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node: [20.x]
        browser: [safari]
    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v3
    - name: Run Tests (${{ matrix.browser }})
      uses: DevExpress/testcafe-action@v0.0.6
      with:
        version: "3.7.2"
        args: ${{ matrix.browser }} tests/      
