name: TestCafe Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests - (WINDOWS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [12.x, 16.x]
        browser: [ie]
        headlessbrowser: [edge, chrome, firefox]
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Run Tests (All Browsers - Headless)
      uses: DevExpress/testcafe-action@latest
      with:
          args: ${{ matrix.headlessbrowser }}:headless -c 6 tests/
    - name: Run Tests (IE)
      uses: DevExpress/testcafe-action@latest
      with:
          args: ${{ matrix.browser }} -c 6 tests/
          
