name: TestCafe Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests - (WINDOWS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [12.x, 16.x]
        browser: [edge:headless, chrome:headless, firefox:headless, ie]
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Run Tests ${{ matrix.node }}
      uses: DevExpress/testcafe-action@latest
      with:
          args: "${{ matrix.node }} -c 6 tests/"
          
