# CI/Manual Trigger
name: TestCafe Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test1:
    name: TestCafe Tests - (WINDOWS/HEADLESS)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [14.x, 16.x]
        headlessbrowser: [edge, chrome, firefox]
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Run Tests (${{ matrix.headlessbrowser }}) Headless
      uses: DevExpress/testcafe-action@latest
      with:
          args: ${{ matrix.headlessbrowser }}:headless -c 6 tests/
          
  test2:
    name: TestCafe Tests - (WINDOWS/IE)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [14.x, 16.x]
        browser: [ie]
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Run Tests (${{ matrix.browser }})
      uses: DevExpress/testcafe-action@latest
      with:
          args: ${{ matrix.browser }} tests/
          
  test3:
    name: TestCafe Tests - (UBUNTU)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.x, 16.x]
        headlessbrowser: [chrome, firefox]
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Run Tests (${{ matrix.headlessbrowser }}) Headless
      uses: DevExpress/testcafe-action@latest
      with:
          args: ${{ matrix.headlessbrowser }}:headless -c 6 tests/
          
